version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    depends_on:
      - theciu
    networks:
      - sail

  theciu:
    build: .
    ports:
      - "8888:9000"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    depends_on:
      - mariadb
    networks:
      - sail

  mariadb:
    image: 'mariadb:10'
    command: --max_allowed_packet=2048M
    ports:
      - '${FORWARD_DB_PORT:-3308}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sail-mariadb:/var/lib/mysql'
      - ./mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge
volumes:
  sail-mariadb:
    driver: local

