version: '3'
services:
  mariadb:
    image: 'mariadb:10'
    command: --max_allowed_packet=2048M
    ports:
      - '127.0.0.1:${FORWARD_DB_PORT:-3308}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - '/home/theciu-data:/var/lib/mysql'
      - ./mariadb/init:/docker-entrypoint-initdb.d
    network_mode: bridge
    networks:
      - network1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

networks:
  network1:
     ipam:
      config:
        - subnet: 58.187.188.0/24
          gateway: 58.187.188.1
          ip_range: 58.187.188.20/32

