version: '3'
services:
  mariadb:
    image: 'mariadb:10'
    command: --max_allowed_packet=2048M
    ports:
      - '${FORWARD_DB_PORT:-3308}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Ho_Chi_Minh'
    volumes:
      - '/home/theciu-data:/var/lib/mysql'
      - ./mariadb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    restart: always
    networks:
      - theciu-db
  backup:
    image: tuanhm2703/google-drive-backup:latest
    volumes:
      - './credentials.json:/credentials.json'
      - '/home/theciu-data:/backup'
      - './crontab.txt:/crontab.txt'
      - './my-script.sh:/my-script.sh'
    command: tail -f /dev/null
    restart: always
    networks:
      - theciu-db
  supervisor:
    build:
      context: ./supervisor
      dockerfile: Dockerfile
    container_name: supervisor
    volumes:
      - /home/theciu.vn/public_html:/var/www/html
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - theciu-db
  supervisor-beta:
    build:
      context: ./supervisor
      dockerfile: Dockerfile
    container_name: beta-supervisor
    volumes:
      - /home/beta.theciu.vn/public_html:/var/www/html
      - ./supervisor/beta-supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - theciu-db
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /home/beta.theciu.vn/s3:/data
    deploy:
      resources:
        limits:
          cpus: '0.2' # Set the CPU limit to 30%
          memory: 500M # Set the memory limit to 500MB

    networks:
      - theciu-db
    restart: always
networks:
  theciu-db:
    driver: bridge
